### ISSUE TITLE
Cleaning up unused dependencies.

### ISSUE THREAD

**Issue by wholetthedogsout** [FabMo/FabMo-Engine#156]
Remove no longer used dependencies.

**Comment by wholetthedogsout** [comment]
@ryansturmer getting error with npm install with dbus@0.2.12  only place i find it in the files is in the npm debug log. Any ideas?

**Comment by ryansturmer** [comment]
I would focus on the dashboard dependencies rather than those in the engine... the dbus dependency though is for the wireless connection manager for the intel edison, it probably will crash if you try to install  it.  If you are having difficulty getting the engine to run, you can take connman-simplified out of the package.json temporarily

**Comment by wholetthedogsout** [comment]
@ryansturmer Thanks. I just wasn't sure which module in the package.json the dbus was affiliated with.

**Comment by ryansturmer** [comment]
I think we've done enough dependency cleanup for now, before having really gutted the thing for unneeded framework stuff and components.
