### ISSUE TITLE
Inch vs MM configuration Issues

### ISSUE THREAD

**Issue by MaxFrenzy** [FabMo/FabMo-Engine#443]
I noticed that recently stepper units has been added to the G2.json config. I'm not sure why that was placed in there because as far as I know, it is not a G2 parameter, unless synthethos hasn't updated their wiki. It's my understanding that step angle, distance per rev, and microstep value are the required parameters and should be sufficient info to provide the data required to derive unit values for FabMo. My assumption is that the unit values are being used for the SBP runtime. Perhaps you can fill me in on the logic behind the switch? Maybe it has to do with issues I've noticed switching back and forth between inch/mm, perhaps due to irrational numbers and/or decimal truncation.

* Unit value ends up being slightly different. Ex: in MM my unit value is 320 (1.8, 8x step, 5mm Travel per rev). When I configure in MM, then toggle from inches and back to MM, I end up with 319.91682162637716. That ends up being close enough to be negligible in practice, though it would be nice to just have it go back to its original setting. However, if I configure in MM, set unit value to 320 and switch to inches, I get 8125.952260030473, and that seems off.  So if I do the calculation on my machine for unit values in inches, here is how I've gone about it. My ball screw pitch is 5mm. 25.4/5mm = 5.08 revolutions per inch. 200 steps per revolution * 5.08mm * 8x microstepping = 8,128.

Similarly, after configuring in MM and switching to inches, then back to MM, I find the jerk values are slightly different. Max jerk previously set at 100 is now 102. High speed set at 200 is now 203, etc. Speaking of jerk values, I was also curious about how the default jerk value of 50 inches/sec^3 was derived.. The G2 wiki used 50 as a starting point for a moderate performance machine, but the value is in millimeters. Note, numbers under 1 million are multiplied by 1 million. For an equivalent jerk value of 50mm/min^3 (50 million), the inch value is 1,968,504 (approx 2 million). Thus, the jerk value in fabmo for inches would be 2 for 50mm, 4 for 100mm, 8 for 200mm, etc. When switching to MM when the default jerk values that are set at 50 in inch mode, you end up with a very high MM value of 1270, reflecting a jerk value in the billions. It's certainly possible a machine could handle that, I was just curious that their recommended default mm value happened to be the same value used in inches. 

In the machine configuration, when switching between inches/MM, the values are labels are not converted/adjusted. When in MM mode, you can enter MM values into the manual speed fields (even though they say inches) and have it work, but when you switch back to inches, your manual movement speed is going to be ridiculously high (e.g. lets say you set x/y speed to 50.8mm or 2" per second..when you're back in inch mode, that's going to be an issue). Similarly, if you configured for inches and then switched to MM, the machine config for manual movement values will still retain their previous inch value, but act in MM...thus a manual movement speed of 3 inches/sec behaves as 3mm per second when you switch. Values for machine envelope are behaving similarly, not changing field labels or converting.

Hopefully this all makes sense. Please let me know if I'm overlooking something. 

Thanks

**Comment by ryansturmer** [comment]
@MaxFrenzy 

Thank you for your thoughtful write-up.  I'll address all of your issues here, but in the future, if you can submit one issue per issue, that is helpful to us in getting everything sorted.  My read of your text above produces 4 issues:

1. What's the deal with the new unit value thing?
2. Going back and forth between inches and metric produces funny decimal errors
3. Where does the default jerk come from?
4. Some values don't change units when it seems like they should, when switching from in/mm and back

All good questions.

**1. What's the deal with the new units?**

This is not just an OpenSBP runtime thing, and in fact will be the default unit specification going forward.  There are two reasons for this.  One is, that for systems that don't use stepper motors, (such as step/direction converted servos) or systems that have unconventional gearing systems or microstep configurations, the tr/mi/sa convention of setting the units has been confusing for customers.  The thinking early on in the design of TinyG was that splitting the units up in this way made it easier for developers to enter their parameters into the system, but the truth of it turns out to be that communicating a single number that just represents "steps per unit" is far simpler.  It's easy enough to do the calculation (Which you have done yourself above) and so we've decided to stick with this as our unit setting technique moving forward. The second reason is that there are decimal precision issues in using the tr/mi/sa for certain unit value settings, which are obviated by simply setting one number (and not suffering precision loss in the computation in G2 itself, because after all, G2 is simply calculating this number and using it internally, anyway.) This doesn't come about for many configurations, but as we have started to use fabmo on some very large, high-resolution machines, this became an issue for us.  Having said all this, you should know that there is a new g2 firmware build that supports this unit value strategy (the configuration setting is `su` = steps/unit) and for things to work properly on the latest master in fabmo, you must flash this firmware.  The `su` setting will likely be a part of the stock G2 build eventually, but for now, it only exists in our configuration.  You can in fact still use tr/mi/sa to set things up, but these settings are no longer in the defaults, and no longer exposed in the dash.

**2. Switching back and forth produces funny unit conversions**

On my setup, I don't see any of the strange decimal issues, probably because I am running the firmware that handles the new unit system properly.  Many of G2s internal parameters are generated using the steps/unit as a base, so if it's squirrely, that is likely your cause.

**3. Where does the default jerk come from**

The fact that we set the default jerk to 50 (in inches) and that the G2 recommendation is 50 (in mm) turns out to be a coincidence.  50 is a value that experimentally yields good results on our tool.  We found 25 to be a good "safe" (but slow) value on our machines, and 100 to be pretty aggressive for most applications.  The defaults that ship with FabMo are currently the values that work well on the ShopBot Handibot, since that's our flagship FabMo tool.  In future releases of FabMo we're going to introduce "profiles" of some sort that will allow us to encode optimal configurations for many tools, and switch easily between them.

**4. Some values don't change units when it seems like they should, when switching from in/mm and back.**

You got me there - that's just a bug (or rather an oversight) - I'll open tickets and get these things fixed.  I'll tag you in them in case you want to follow along.
