### ISSUE TITLE
Up/Down Arrows displayed next to running file name.

### ISSUE THREAD

**Issue by SW0rden** [FabMo/FabMo-Engine#446]
A pair of scroll up/down arrows are displayed in the pop up Stop Bar next to the running file name.

Having the running file name displayed there is a bit of a redundancy, since it's displayed in the 'Now Running' box.  This might be a good place for displaying the elapsed time to go with the percentage indicator.  Items in the Stop Bar could use a bit of padding between them and the taskbar for desktop/laptop.

![up_down arrows](https://cloud.githubusercontent.com/assets/18059548/16238399/fc4176fe-37a5-11e6-894d-1fb3d823693c.jpg)

**Comment by ryansturmer** [comment]
We don't see the redundancy because there is no guarantee that the user will remain in the job manager while the file cuts, and indeed, it is not required that they go through the job manager to start a file, in some cases.  The elapsed time will likely go inside the progress bar itself, or next to it.  We will fix the scrollbar issue, though.

**Comment by wholetthedogsout** [comment]
Is this in firefox or chrome? and on PC? @SW0rden

**Comment by ryansturmer** [comment]
We've seen it on PC/Chrome, and i've seen it on mac firefox as well, I think.

**Comment by wholetthedogsout** [comment]
Thanks!

**Comment by SW0rden** [comment]
Sorry, both Chrome and FF on desktop/laptop.

**Comment by wholetthedogsout** [comment]
Should be fixed, never been able to replicate myself but so please test.

**Comment by SW0rden** [comment]
Looks good now.
