### ISSUE TITLE
Trying to z-zero in DT Fireup just..doesn't do anything.

### ISSUE THREAD

**Issue by obra** [FabMo/FabMo-Engine#926]
Clicking the button doesn't generate any response in the UI.

![image](https://user-images.githubusercontent.com/45416/172735812-5e7f85f0-2c5f-4f06-b7a3-997919bceef0.png)

In the browser's log, I see:
![image](https://user-images.githubusercontent.com/45416/172735890-90de94bd-2a39-460a-85c1-34ee7ef19150.png)

Other moves with the control pad work fine.

After a manual move, I can z home:

![image](https://user-images.githubusercontent.com/45416/172736100-93b4ce80-f7b2-44a7-a5e8-af1663b9f0db.png)

**Comment by obra** [comment]
I'm unable to repro as of right now. I have not yet updated fabmo, but am about to.

Software Version
47884-v3.1.8-dev
G2 Firmware Version
v101.57.36

Please feel free to close this or tag it in whatever way you folks use for "customer can't prove the problem happens" (or ask me to do the same. I just don't know what your standard practice is)

**Comment by kyle-kingsbury** [comment]
Rob,
How do we want to handle this?

**Comment by RobMackie** [comment]
I figure if we're still trying to reproduce it we'll tag it "reproduce" and
that means if anyone ever reproduces it, we'll give it attn, otherwise it
just sits as a "apparently seen once, may have been fixed, may have had a
transient cause or  may be user observation error - won't know until we see
it again."  If it last long enough (no idea how long yet) without being
reproduced, we'll close it as "reproduce" or if we can figure out it was a
misoberseveratioin (i.e. if jesse says - oh is see what i did, it didn't
really fail, i just misunderstood ) - then we'll mark it junk and close it.

Does that sound about right?

And Jesse - we're figuring this out live as we go. there were one set of
practices and now new ones are emerging. So opinions and suggestions
welcome, sometimes adopted, sometimes not.

Rob.

**Comment by obra** [comment]
On Mon, Jun 13, 2022, at 1:23 PM, Kyle Kingsbury wrote:
> 
> 
> That is strange. When I run it output 4 turns on, the stop button appears in the footer, I can see the z raise up and slowly lower until it is below 0. Then I get an alarm "Target Not Triggered! (Started above prox switch?)" (I am running on a simulater with no prox switch). When you ran it nothing happened at all? What is your FabMo software version and firmware version?
> 

I'll pull versions off the mill when I'm next down in the shop, but both are the as-shipped versions you sent out.  It doesn't fail reliably. It just seems to get stuck sometimes.
